### ISSUE TITLE
setup.py broken

### ISSUE THREAD

**Issue by rafaduran** [jkehler/unshortenit#10]
See:

```bash
$ mkvirtualenv scratch
New python executable in scratch/bin/python
Installing setuptools, pip...done.
Downloading/unpacking ipdb
  Downloading ipdb-0.9.0.tar.gz
  Running setup.py (path:/home/rduran/.virtualenvs/scratch/build/ipdb/setup.py) egg_info for package ipdb
    
Downloading/unpacking ipython>=0.10 (from ipdb)
  Downloading ipython-4.1.2-py2-none-any.whl (736kB): 736kB downloaded
Requirement already satisfied (use --upgrade to upgrade): setuptools in /home/rduran/.virtualenvs/scratch/lib/python2.7/site-packages (from ipdb)
Downloading/unpacking pickleshare (from ipython>=0.10->ipdb)
  Downloading pickleshare-0.6-py2.py3-none-any.whl
Downloading/unpacking pexpect (from ipython>=0.10->ipdb)
  Downloading pexpect-4.0.1.tar.gz (143kB): 143kB downloaded
  Running setup.py (path:/home/rduran/.virtualenvs/scratch/build/pexpect/setup.py) egg_info for package pexpect
    
Downloading/unpacking simplegeneric>0.8 (from ipython>=0.10->ipdb)
  Downloading simplegeneric-0.8.1.zip
  Running setup.py (path:/home/rduran/.virtualenvs/scratch/build/simplegeneric/setup.py) egg_info for package simplegeneric
    
Downloading/unpacking traitlets (from ipython>=0.10->ipdb)
  Downloading traitlets-4.1.0-py2.py3-none-any.whl (65kB): 65kB downloaded
Downloading/unpacking decorator (from ipython>=0.10->ipdb)
  Downloading decorator-4.0.9-py2.py3-none-any.whl
Downloading/unpacking path.py>=6.2 (from pickleshare->ipython>=0.10->ipdb)
  Downloading path.py-8.1.2-py2.py3-none-any.whl
Downloading/unpacking ptyprocess>=0.5 (from pexpect->ipython>=0.10->ipdb)
  Downloading ptyprocess-0.5.1-py2.py3-none-any.whl
Downloading/unpacking ipython-genutils (from traitlets->ipython>=0.10->ipdb)
  Downloading ipython_genutils-0.1.0-py2.py3-none-any.whl
Installing collected packages: ipdb, ipython, pickleshare, pexpect, simplegeneric, traitlets, decorator, path.py, ptyprocess, ipython-genutils
  Running setup.py install for ipdb
    
    Installing ipdb script to /home/rduran/.virtualenvs/scratch/bin
  Running setup.py install for pexpect
      File "/home/rduran/.virtualenvs/scratch/lib/python2.7/site-packages/pexpect/async.py", line 16
        transport, pw = yield from asyncio.get_event_loop()\
                                 ^
    SyntaxError: invalid syntax
    
    
  Running setup.py install for simplegeneric
    
Successfully installed ipdb ipython pickleshare pexpect simplegeneric traitlets decorator path.py ptyprocess ipython-genutils
Cleaning up...
(scratch)rduran@rdc-H81M-S2H:~/workspace/unshortenit$ python setup.py test
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    import unshortenit
  File "/home/rduran/workspace/unshortenit/unshortenit/__init__.py", line 8, in <module>
    from .base import unshorten
  File "/home/rduran/workspace/unshortenit/unshortenit/base.py", line 16, in <module>
    import requests
ImportError: No module named requests
```

**Comment by jkehler** [comment]
Everything is working as intended. You need to install the deps before you can run the unit tests.
