### ISSUE TITLE
Link causes unshortenit to hang, timeout doesn't fire

### ISSUE THREAD

**Issue by geofurb** [jkehler/unshortenit#17]
The link "http://fb.me/36vAPSlVl" causes unshortenit to churn CPU cycles and get nowhere. Stalls indefinitely, even with timeout flagged. Haven't debugged in-depth. Tested only on Ubuntu 16.04 so far.

**Comment by geofurb** [comment]
Here's my stack trace from the python3.5 interpreter:

url, code = unshortenit.unshorten('http://fb.me/36vAPSlVl')
^C
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-31-86fd8c9c7581>", line 1, in <module>
    url, code = unshortenit.unshorten('http://fb.me/36vAPSlVl')
  File "/usr/local/lib/python3.5/dist-packages/unshortenit/base.py", line 410, in unshorten
    uri, status = unshortener.unwrap_30x(uri, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/unshortenit/base.py", line 101, in unwrap_30x
    r = requests.head(uri, headers=HTTP_HEADER, timeout=self._timeout)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 93, in head
    return request('head', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 162, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 137, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 81, in create_connection
    sock.connect(sa)

**Comment by jkehler** [comment]
I believe this was because FB uses meta refresh links. Your sample link is now supported and working fine for me in the 0.4.0 release.
